# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          export GOPROXY=https://goproxy.cn,direct
          go mod download
          GOOS=linux GOARCH=amd64 go build -o main ./main.go

      # 修改为自己的镜像仓库
      - name: deploy scheduler
        run: |
          echo "Aa123456" | docker login --username=1126254578 ccr.ccs.tencentyun.com --password-stdin
          docker build -t ccr.ccs.tencentyun.com/comeonjy/account:v0.0.1 .
          docker push ccr.ccs.tencentyun.com/comeonjy/account:v0.0.1

      - name: report
        run: |
          git branch --show-current
          git log -1 --pretty=format:"%cn %s"